version: '3'
services:
  mongo:
    image: mongo
    container_name: test_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: test_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  contacts-app:
    image: contacts-app
    container_name: contacts-app
    restart: always
    environment:
      APP_NAME: contacts-app
      LOG_LEVEL: DEBUG
      MANDATORY_HEADERS: '["firstName", "lastName", "email", "companyName"]'
      MONGO_URI: mongodb://root:root@localhost:27017/
      MONGO_DB_NAME: contacts
      JWT_SECRET: your-256-bit-secret
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 8000:8000
volumes:
  mongo_db: {}
